var isDone = false;
console.log(isDone);
var decimal = 6;
console.log(decimal);
var color = "blue";
console.log(color);
// let FullName:string = "Thanhpt";
// let sentence:string =  `${ FullName } is very handsome`;
var fullName = "Thanhpt";
var age = 24;
var sentence = fullName + " is very handsome.\n\nI'll be " + (age + 1) + " years old next month.";
console.log(sentence);
